- name: "ensure apache2 is installed"
  apt:
    pkg: apache2
- name: copy template index 
  template: 
    src: index.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: 0644

- name: "Copiar fichero al servidor remoto"
  copy:
    src: fichero.html
    dest: /var/www/html/fichero.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: "Copiar fichero de configuración y reiniciar el servicio"
  copy:
    src: etc/apache2/ports.conf
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart apache2

- name: "Añadir comentario de prueba en Apache config"
  lineinfile:
    path: /etc/apache2/ports.conf
    line: "# Prueba de handler, modificación de receta"
    state: present
  notify:
    - restart apache2
